name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the application
        run: |
          npm run build

      - name: Deploy updated files to EC2 (exclude node_modules)
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          # Save SSH key to file
          echo "${{ secrets.SSH_SECRET_KEY }}" > key.pem
          chmod 600 key.pem

          # Rsync everything except node_modules
          rsync -az --update \
          --exclude 'node_modules' \
          --exclude '.git' \
          --exclude '.github' \
          --exclude '.env' \
          --exclude '.prettierrc' \
          --exclude 'tsconfig*.json' \
          --exclude 'README.md' \
          --exclude 'vercel.json' \
          -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ $USER@$HOST:/home/ubuntu/vital-signs

          # Restart app on EC2 using the new build in lib
          ssh -i key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /home/ubuntu/vital-signs
            if ! pm2 list | grep -q 'app'; then
              echo "Starting the app with PM2"
              pm2 start lib/main.js --name app
            else
              echo "App already running, restarting..."
              pm2 restart all
            fi
          EOF
